name: CI App X

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./diretorio-app/requirements.txt

    - name: Run tests
      run: pytest

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ lucasolidev }}
        password: ${{ dckr_pat_RoskiHeFwqg8qHa1VBOwex7xmrU }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./diretorio-app
        push: true
        tags: docker.io/lucasolidev/nome-do-app:latest